[hebaov2] Allow operator to charge less when creating a new wallet
Loopring/protocols pull request #2540
Opened 2021-07-29 07:14 UTC by kongliangzhong

2021-07-29 12:11 UTC, dong77 requested changes

2021-07-29 12:11 UTC, dong77 commented on packages/hebao_v2/contracts/base/WalletFactory.sol
> +        uint      maxFeeAmount;
I suggest that we remove `feeAmount` from this struct. And pass in feeAmount to `createWallet` as a seperate parameter directly:

```solidity
 function createWallet(
        WalletConfig calldata config,
        uint                  salt,
        uint                  feeAmount
        )

```

2021-07-29 14:26 UTC, Brechtpd commented
@dong77 I was wrong about the front-running/MEV risk. The `feeRecipient` is signed by the wallet owner so there is no reason why anyone else would want to deploy the wallet instead (even with the fee always set to maxFee).

2021-07-29 16:09 UTC, Brechtpd submitted a review, later dismissed

2021-07-30 00:47 UTC, dong77 commented on packages/hebao_v2/contracts/base/WalletFactory.sol
> +        require(feeAmount <= config.maxFeeAmount, "INVALID_FEE_AMOUNT");
Please move this check out of this function so we can remove  the`feeAmount` parameter.

2021-07-30 04:01 UTC, dong77 approved these changes

2021-07-30 04:01 UTC, merged